public enum Item {
    PRO_FLASHLIGHT = 1,
    ZAP_GUN = 5,
    FLASHLIGHT = 6,
    SHOVEL = 7,
    WALKIE_TALKIE = 7,
    LOCKPICKER = 8,
    BOOMBOX = 9,
    STUN_GRENADE = 12,
    JETPACK = 13,
    TZP_INHALANT = 15,
    RADAR_BOOSTER = 16,
    EXTENSION_LADDER = 17,
}
