name: Format

on:
  push:
    branches: main
    paths:
      - .github/workflows/formatter.yml
      - .editorconfig
      - lc-hax/Scripts/**/*.cs
  pull_request_target:
    paths:
      - .github/workflows/formatter.yml
      - .editorconfig
      - lc-hax/Scripts/**/*.cs

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Cache .NET tools
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.nuget/packages
          key: dotnet-tools-${{ runner.os }}-${{ hashFiles('.config/dotnet-tools.json') }}
          restore-keys: dotnet-tools-${{ runner.os }}-

      - name: Setup .NET
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
        with:
          dotnet-version: 8.0.x

      - name: Restore tools
        run: dotnet tool restore

      - name: Format scripts
        run: |
          dotnet format lc-hax
          dotnet format analysers

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Commit changes
        run: |
          git add .
          git commit -m "style: format scripts" || true
          git push
