name: Update Resource(s)

on:
  pull_request:
  push:
    paths:
      - .github/workflows/update-resource.yml
      - lc-hax/*.csproj

concurrency: Format-Resource-${{ github.ref }}
permissions: {}
env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  PATCH_NAME: format.patch
  ARTIFACT_NAME: format-patch

jobs:
  update:
    runs-on: ubuntu-slim
    outputs:
      patched: ${{ steps.patch.outputs.patched }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Cache .NET tools
        uses: actions/cache@v5.0.4
        with:
          path: ~/.nuget/packages
          key: dotnet-tools-${{ runner.os }}-${{ hashFiles('.config/dotnet-tools.json') }}
          restore-keys: dotnet-tools-${{ runner.os }}-

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: 10.x

      - name: Restore tools
        run: dotnet tool restore

      - name: Update Resource
        run: dotnet script scripts/UpdateEmbeddedResource.csx
        env:
          CSPROJ_PATH: lc-hax/lc-hax.csproj

      - name: Upload format patch
        id: patch
        uses: winstxnhdw/actions/upload-patch@main

  push:
    if: needs.update.outputs.patched
    needs: update
    uses: winstxnhdw/actions/.github/workflows/format-push.yml@main
    secrets:
      token: ${{ secrets.PAT }}
    permissions:
      contents: write
